import type {
  Recording,
  ScheduleAssignment,
  Site,
  StudyState,
  TeamMember,
} from "../domain/models";

const stamp = "2026-09-08T09:00:00.000Z";
const recordings: Recording[] = [
  {
    id: "rec-underpass",
    catalogId: "SC-26-001",
    title: "Underpass reverb at dawn",
    source: "Lin Qiao",
    recordedOn: "2026-06-14",
    format: "WAV",
    location: "Mason Street underpass",
    summary:
      "Footsteps, bicycle tires, and the first bus fold into a long concrete echo.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 154,
    },
    signalRole: "arrival",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["mobility", "morning", "echo"],
    color: "#d7654e",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-market",
    catalogId: "SC-26-002",
    title: "Market bell sequence",
    source: "Amina Patel",
    recordedOn: "2026-06-18",
    format: "WAV",
    location: "Riverside produce market",
    summary:
      "Vendor bells, crate wheels, and short greetings form a changing lunchtime pulse.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 218,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "draft",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["market", "voices", "work"],
    color: "#7c6aa6",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-tram",
    catalogId: "SC-26-003",
    title: "Tram brake chorus",
    source: "Rosa Mendes",
    recordedOn: "2026-06-20",
    format: "FLAC",
    location: "East Loop platform",
    summary:
      "A layered study of arriving trams, platform announcements, and departing doors.",
    audioSpec: {
      sampleRate: 96000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 187,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "metal", "rhythm"],
    color: "#2f7c75",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-courtyard",
    catalogId: "SC-26-004",
    title: "Courtyard conversation",
    source: "North Block listening circle",
    recordedOn: "2026-06-23",
    format: "WAV",
    location: "North Block courtyard",
    summary:
      "Neighbors discuss the shade trees while children play beyond the microphone.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 241,
    },
    signalRole: "voice",
    sensitivity: "restricted",
    transcriptStatus: "draft",
    consentStatus: "pending",
    isFeatured: true,
    tags: ["oral history", "neighborhood", "care"],
    color: "#c7903d",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-drain",
    catalogId: "SC-26-005",
    title: "Storm drain resonance",
    source: "Riverside youth lab",
    recordedOn: "2026-06-26",
    format: "WAV",
    location: "Canal walk",
    summary:
      "Rainwater and passing trains turn the storm drain into a low, shifting instrument.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 201,
    },
    signalRole: "voice",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["water", "weather", "youth"],
    color: "#3f6fa8",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-workshop",
    catalogId: "SC-26-006",
    title: "Ceramic workshop pulse",
    source: "Jae Min",
    recordedOn: "2026-07-01",
    format: "FLAC",
    location: "Clay Lane studios",
    summary:
      "Throwing wheels, trimming tools, and a quiet count-in before firing.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 166,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["craft", "hands", "rhythm"],
    color: "#8c9474",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-bus",
    catalogId: "SC-26-007",
    title: "Evening bus loop",
    source: "Milo Chen",
    recordedOn: "2026-07-04",
    format: "WAV",
    location: "Route 11 terminus",
    summary:
      "The last loop of the evening: ticket beeps, a driver’s goodbye, and an emptying carriage.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 193,
    },
    signalRole: "departure",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "evening", "routine"],
    color: "#a55f72",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-park",
    catalogId: "SC-26-008",
    title: "Park fence harmonics",
    source: "Elena Matic",
    recordedOn: "2026-07-08",
    format: "WAV",
    location: "Juniper Park",
    summary:
      "Wind and a loose fence panel make a soft tonal figure beside an afternoon game.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 128,
    },
    signalRole: "departure",
    sensitivity: "sensitive",
    transcriptStatus: "missing",
    consentStatus: "restricted",
    isFeatured: false,
    tags: ["park", "wind", "play"],
    color: "#597b8e",
    createdAt: stamp,
    updatedAt: stamp,
  },
];
const sites: Site[] = [
  {
    id: "site-threshold",
    name: "Threshold listening",
    shortLabel: "Threshold",
    prompt:
      "What changes when you stop and listen before crossing into the neighborhood?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#d7654e",
    sequence: 0,
    recordingIds: ["rec-underpass"],
  },
  {
    id: "site-rhythm",
    name: "Daily rhythms",
    shortLabel: "Rhythms",
    prompt:
      "Which repeated sounds tell us how work, transit, and care share a day?",
    maxDurationSeconds: 540,
    maxClips: 3,
    quietSpace: false,
    hasSeating: true,
    color: "#7c6aa6",
    sequence: 1,
    recordingIds: ["rec-market", "rec-tram"],
  },
  {
    id: "site-voices",
    name: "Shared voices",
    shortLabel: "Voices",
    prompt:
      "Whose voices need context, consent, or a slower place to be heard?",
    maxDurationSeconds: 480,
    maxClips: 2,
    quietSpace: true,
    hasSeating: true,
    color: "#2f7c75",
    sequence: 2,
    recordingIds: ["rec-courtyard"],
  },
  {
    id: "site-return",
    name: "Return and release",
    shortLabel: "Return",
    prompt: "What should remain audible after the route ends?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#597b8e",
    sequence: 3,
    recordingIds: ["rec-bus"],
  },
];

const SATURDAY = "2026-09-19";
const SUNDAY = "2026-09-20";

const teamMembers: TeamMember[] = [
  {
    id: "member-lin",
    name: "Lin Qiao",
    role: "Field recordist",
    availableDates: [SATURDAY, SUNDAY],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "member-amina",
    name: "Amina Patel",
    role: "Consent lead",
    availableDates: [SATURDAY, SUNDAY],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "member-milo",
    name: "Milo Chen",
    role: "Route marshal",
    availableDates: [SATURDAY, SUNDAY],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "member-rosa",
    name: "Rosa Mendes",
    role: "Audio specialist",
    availableDates: [SATURDAY],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "member-jae",
    name: "Jae Min",
    role: "Volunteer coordinator",
    availableDates: [SATURDAY, SUNDAY],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "member-elena",
    name: "Elena Matic",
    role: "Accessibility host",
    availableDates: [SUNDAY],
    createdAt: stamp,
    updatedAt: stamp,
  },
];

const scheduleAssignments: ScheduleAssignment[] = [
  // Saturday: Rhythms stays uncovered so leads see the gap immediately.
  {
    id: "assign-sat-threshold-lin",
    memberId: "member-lin",
    siteId: "site-threshold",
    date: SATURDAY,
    startsAt: "09:00",
    endsAt: "10:30",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sat-threshold-jae",
    memberId: "member-jae",
    siteId: "site-threshold",
    date: SATURDAY,
    startsAt: "10:30",
    endsAt: "12:00",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sat-voices-amina",
    memberId: "member-amina",
    siteId: "site-voices",
    date: SATURDAY,
    startsAt: "09:30",
    endsAt: "11:30",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sat-voices-rosa",
    memberId: "member-rosa",
    siteId: "site-voices",
    date: SATURDAY,
    startsAt: "10:00",
    endsAt: "11:00",
    note: "Checking restricted-clip consent window",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sat-return-milo",
    memberId: "member-milo",
    siteId: "site-return",
    date: SATURDAY,
    startsAt: "14:00",
    endsAt: "15:00",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    // Deliberate overlap: Milo is double-booked across the city on Saturday.
    id: "assign-sat-threshold-milo-conflict",
    memberId: "member-milo",
    siteId: "site-threshold",
    date: SATURDAY,
    startsAt: "14:30",
    endsAt: "16:00",
    createdAt: stamp,
    updatedAt: stamp,
  },
  // Sunday: Rosa is on leave, so the Voices shift loses its only cover.
  {
    id: "assign-sun-threshold-lin",
    memberId: "member-lin",
    siteId: "site-threshold",
    date: SUNDAY,
    startsAt: "09:00",
    endsAt: "11:00",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sun-rhythm-jae",
    memberId: "member-jae",
    siteId: "site-rhythm",
    date: SUNDAY,
    startsAt: "11:00",
    endsAt: "13:00",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sun-voices-rosa-absent",
    memberId: "member-rosa",
    siteId: "site-voices",
    date: SUNDAY,
    startsAt: "09:30",
    endsAt: "11:00",
    note: "Standing shift before weekend leave was confirmed",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "assign-sun-return-milo",
    memberId: "member-milo",
    siteId: "site-return",
    date: SUNDAY,
    startsAt: "14:00",
    endsAt: "16:00",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    // Elena hosts the return loop; Voices only carries Rosa's absent morning shift.
    id: "assign-sun-return-elena",
    memberId: "member-elena",
    siteId: "site-return",
    date: SUNDAY,
    startsAt: "13:00",
    endsAt: "14:30",
    createdAt: stamp,
    updatedAt: stamp,
  },
];

export function createSeedStudy(): StudyState {
  return structuredClone({
    version: 3,
    revision: 0,
    updatedAt: stamp,
    project: {
      id: "signal-commons-2026",
      title: "Signal Commons: Listening Across the City",
      fieldArea: "Riverside neighborhoods",
      listeningQuestion:
        "How do everyday crossings, work, and care sound when residents lead the record?",
      publicationDate: "2026-10-02",
      stage: "review",
    },
    recordings,
    sites,
    issues: [
      {
        id: "issue-consent",
        title: "Confirm courtyard release scope",
        description:
          "The listening circle needs to confirm whether the full conversation can be included in the public route.",
        severity: "critical",
        status: "open",
        recordingId: "rec-courtyard",
        siteId: "site-voices",
        owner: "Amina Patel",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "issue-transcript",
        title: "Add transcript for storm drain clip",
        description:
          "Prepare a concise transcript and sound description before the youth lab clip is released.",
        severity: "warning",
        status: "in-progress",
        recordingId: "rec-drain",
        owner: "Lin Qiao",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    preferences: { pace: "steady", accessPriority: 70, listenerCount: 6 },
    schedule: {
      weekendStart: SATURDAY,
      weekendEnd: SUNDAY,
      members: teamMembers,
      assignments: scheduleAssignments,
    },
    auditLog: [],
    release: null,
  });
}
