import type {
  ConsentGrant,
  Recording,
  Site,
  StudyState,
} from "../domain/models";

const stamp = "2026-09-08T09:00:00.000Z";
const recordings: Recording[] = [
  {
    id: "rec-underpass",
    catalogId: "SC-26-001",
    title: "Underpass reverb at dawn",
    source: "Lin Qiao",
    recordedOn: "2026-06-14",
    format: "WAV",
    location: "Mason Street underpass",
    summary:
      "Footsteps, bicycle tires, and the first bus fold into a long concrete echo.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 154,
    },
    signalRole: "arrival",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["mobility", "morning", "echo"],
    color: "#d7654e",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-market",
    catalogId: "SC-26-002",
    title: "Market bell sequence",
    source: "Amina Patel",
    recordedOn: "2026-06-18",
    format: "WAV",
    location: "Riverside produce market",
    summary:
      "Vendor bells, crate wheels, and short greetings form a changing lunchtime pulse.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 218,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "draft",
    consentStatus: "restricted",
    isFeatured: true,
    tags: ["market", "voices", "work"],
    color: "#7c6aa6",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-tram",
    catalogId: "SC-26-003",
    title: "Tram brake chorus",
    source: "Rosa Mendes",
    recordedOn: "2026-06-20",
    format: "FLAC",
    location: "East Loop platform",
    summary:
      "A layered study of arriving trams, platform announcements, and departing doors.",
    audioSpec: {
      sampleRate: 96000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 187,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "metal", "rhythm"],
    color: "#2f7c75",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-courtyard",
    catalogId: "SC-26-004",
    title: "Courtyard conversation",
    source: "North Block listening circle",
    recordedOn: "2026-06-23",
    format: "WAV",
    location: "North Block courtyard",
    summary:
      "Neighbors discuss the shade trees while children play beyond the microphone.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 241,
    },
    signalRole: "voice",
    sensitivity: "restricted",
    transcriptStatus: "draft",
    consentStatus: "expired",
    isFeatured: true,
    tags: ["oral history", "neighborhood", "care"],
    color: "#c7903d",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-drain",
    catalogId: "SC-26-005",
    title: "Storm drain resonance",
    source: "Riverside youth lab",
    recordedOn: "2026-06-26",
    format: "WAV",
    location: "Canal walk",
    summary:
      "Rainwater and passing trains turn the storm drain into a low, shifting instrument.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 201,
    },
    signalRole: "voice",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["water", "weather", "youth"],
    color: "#3f6fa8",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-workshop",
    catalogId: "SC-26-006",
    title: "Ceramic workshop pulse",
    source: "Jae Min",
    recordedOn: "2026-07-01",
    format: "FLAC",
    location: "Clay Lane studios",
    summary:
      "Throwing wheels, trimming tools, and a quiet count-in before firing.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 166,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "withdrawn",
    isFeatured: false,
    tags: ["craft", "hands", "rhythm"],
    color: "#8c9474",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-bus",
    catalogId: "SC-26-007",
    title: "Evening bus loop",
    source: "Milo Chen",
    recordedOn: "2026-07-04",
    format: "WAV",
    location: "Route 11 terminus",
    summary:
      "The last loop of the evening: ticket beeps, a driver’s goodbye, and an emptying carriage.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 193,
    },
    signalRole: "departure",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "evening", "routine"],
    color: "#a55f72",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-park",
    catalogId: "SC-26-008",
    title: "Park fence harmonics",
    source: "Elena Matic",
    recordedOn: "2026-07-08",
    format: "WAV",
    location: "Juniper Park",
    summary:
      "Wind and a loose fence panel make a soft tonal figure beside an afternoon game.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 128,
    },
    signalRole: "departure",
    sensitivity: "sensitive",
    transcriptStatus: "missing",
    consentStatus: "restricted",
    isFeatured: false,
    tags: ["park", "wind", "play"],
    color: "#597b8e",
    createdAt: stamp,
    updatedAt: stamp,
  },
];

const consents: ConsentGrant[] = [
  {
    id: "grant-underpass",
    recordingId: "rec-underpass",
    status: "active",
    purposes: ["route", "transcript", "archive"],
    grantedBy: "Lin Qiao",
    channel: "Signed release form",
    evidenceRef: "FORM-2026-014",
    note: "Full release for the 2026 listening study.",
    grantedAt: "2026-06-14",
    createdAt: "2026-06-14T18:00:00.000Z",
  },
  {
    id: "grant-market-full",
    recordingId: "rec-market",
    status: "restricted",
    purposes: ["route", "transcript", "archive"],
    grantedBy: "Amina Patel",
    channel: "Email confirmation",
    evidenceRef: "EMAIL-2026-031",
    note: "Initial full release confirmed by email.",
    grantedAt: "2026-06-18",
    supersededAt: "2026-08-20T10:00:00.000Z",
    createdAt: "2026-06-18T17:30:00.000Z",
  },
  {
    id: "grant-market-route-only",
    recordingId: "rec-market",
    status: "restricted",
    purposes: ["route", "transcript"],
    grantedBy: "Amina Patel",
    channel: "Follow-up email",
    evidenceRef: "EMAIL-2026-047",
    note:
      "Scope narrowed on 2026-08-20: on-site route and captions only; public archive withheld pending anonymization.",
    grantedAt: "2026-08-20",
    createdAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "grant-tram",
    recordingId: "rec-tram",
    status: "active",
    purposes: ["route", "transcript", "archive"],
    grantedBy: "Rosa Mendes",
    channel: "Signed release form",
    evidenceRef: "FORM-2026-018",
    note: "Full release, named credit requested.",
    grantedAt: "2026-06-20",
    createdAt: "2026-06-20T19:00:00.000Z",
  },
  {
    id: "grant-courtyard",
    recordingId: "rec-courtyard",
    status: "active",
    purposes: ["route", "transcript"],
    grantedBy: "North Block listening circle",
    channel: "Group meeting minutes",
    evidenceRef: "MINUTES-2026-009",
    note: "Route and transcript use agreed for the field season only.",
    grantedAt: "2026-06-23",
    expiresAt: "2026-08-31",
    createdAt: "2026-06-23T20:00:00.000Z",
  },
  {
    id: "grant-drain",
    recordingId: "rec-drain",
    status: "active",
    purposes: ["route", "transcript", "archive"],
    grantedBy: "Riverside youth lab guardian group",
    channel: "Guardian consent pack",
    evidenceRef: "PACK-2026-YL-05",
    note: "Guardian-approved full release; first names only.",
    grantedAt: "2026-06-26",
    createdAt: "2026-06-26T16:00:00.000Z",
  },
  {
    id: "grant-workshop",
    recordingId: "rec-workshop",
    status: "withdrawn",
    purposes: ["route", "transcript", "archive"],
    grantedBy: "Jae Min",
    channel: "Verbal withdrawal with witness",
    evidenceRef: "NOTE-2026-WITHDRAW-02",
    note:
      "Consent withdrawn on 2026-08-28; the clip cannot be used in new content. Existing releases retain their frozen basis.",
    grantedAt: "2026-07-01",
    supersededAt: "2026-08-28T12:00:00.000Z",
    createdAt: "2026-08-28T12:00:00.000Z",
  },
  {
    id: "grant-bus",
    recordingId: "rec-bus",
    status: "active",
    purposes: ["route", "transcript", "archive"],
    grantedBy: "Milo Chen",
    channel: "Signed release form",
    evidenceRef: "FORM-2026-022",
    note: "Full release for route and study archive.",
    grantedAt: "2026-07-04",
    createdAt: "2026-07-04T18:30:00.000Z",
  },
  {
    id: "grant-park",
    recordingId: "rec-park",
    status: "restricted",
    purposes: ["route", "transcript"],
    grantedBy: "Elena Matic",
    channel: "Signed release with conditions",
    evidenceRef: "FORM-2026-026",
    note:
      "Conditional release: route playback and captions allowed; do not include in the downloadable public archive.",
    grantedAt: "2026-07-08",
    createdAt: "2026-07-08T17:00:00.000Z",
  },
];

const sites: Site[] = [
  {
    id: "site-threshold",
    name: "Threshold listening",
    shortLabel: "Threshold",
    prompt:
      "What changes when you stop and listen before crossing into the neighborhood?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#d7654e",
    sequence: 0,
    recordingIds: ["rec-underpass"],
  },
  {
    id: "site-rhythm",
    name: "Daily rhythms",
    shortLabel: "Rhythms",
    prompt:
      "Which repeated sounds tell us how work, transit, and care share a day?",
    maxDurationSeconds: 540,
    maxClips: 3,
    quietSpace: false,
    hasSeating: true,
    color: "#7c6aa6",
    sequence: 1,
    recordingIds: ["rec-market", "rec-tram"],
  },
  {
    id: "site-voices",
    name: "Shared voices",
    shortLabel: "Voices",
    prompt:
      "Whose voices need context, consent, or a slower place to be heard?",
    maxDurationSeconds: 480,
    maxClips: 2,
    quietSpace: true,
    hasSeating: true,
    color: "#2f7c75",
    sequence: 2,
    recordingIds: ["rec-courtyard"],
  },
  {
    id: "site-return",
    name: "Return and release",
    shortLabel: "Return",
    prompt: "What should remain audible after the route ends?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#597b8e",
    sequence: 3,
    recordingIds: ["rec-bus"],
  },
];
export function createSeedStudy(): StudyState {
  return structuredClone({
    version: 3,
    revision: 0,
    updatedAt: stamp,
    project: {
      id: "signal-commons-2026",
      title: "Signal Commons: Listening Across the City",
      fieldArea: "Riverside neighborhoods",
      listeningQuestion:
        "How do everyday crossings, work, and care sound when residents lead the record?",
      publicationDate: "2026-10-02",
      stage: "review",
    },
    recordings,
    consents,
    sites,
    issues: [
      {
        id: "issue-consent",
        title: "Renew courtyard release scope",
        description:
          "The listening circle's consent expired on 2026-08-31. Renew it or remove the conversation from the public route.",
        severity: "critical",
        status: "open",
        recordingId: "rec-courtyard",
        siteId: "site-voices",
        owner: "Amina Patel",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "issue-transcript",
        title: "Add transcript for storm drain clip",
        description:
          "Prepare a concise transcript and sound description before the youth lab clip is released.",
        severity: "warning",
        status: "in-progress",
        recordingId: "rec-drain",
        owner: "Lin Qiao",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    preferences: { pace: "steady", accessPriority: 70, listenerCount: 6 },
    auditLog: [],
    release: null,
  });
}
