import type {
  ImportBatch,
  LifecycleMeta,
  Recording,
  ReleaseRecord,
  Site,
  StudyState,
} from "../domain/models";

const stamp = "2026-09-08T09:00:00.000Z";
const FIELD_BATCH_ID = "batch-summer-fieldwork";
const AUTUMN_BATCH_ID = "batch-autumn-import";

function lifecycle(
  category: LifecycleMeta["category"],
  anchor: string,
  state: LifecycleMeta["state"] = "within-retention",
  extra: Partial<LifecycleMeta> = {},
): LifecycleMeta {
  return { category, anchor, state, ...extra };
}

const recordings: Recording[] = [
  {
    id: "rec-underpass",
    catalogId: "SC-26-001",
    title: "Underpass reverb at dawn",
    source: "Lin Qiao",
    recordedOn: "2026-06-14",
    format: "WAV",
    location: "Mason Street underpass",
    summary:
      "Footsteps, bicycle tires, and the first bus fold into a long concrete echo.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 154,
    },
    signalRole: "arrival",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["mobility", "morning", "echo"],
    color: "#d7654e",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-market",
    catalogId: "SC-26-002",
    title: "Market bell sequence",
    source: "Amina Patel",
    recordedOn: "2026-06-18",
    format: "WAV",
    location: "Riverside produce market",
    summary:
      "Vendor bells, crate wheels, and short greetings form a changing lunchtime pulse.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 218,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "draft",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["market", "voices", "work"],
    color: "#7c6aa6",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-tram",
    catalogId: "SC-26-003",
    title: "Tram brake chorus",
    source: "Rosa Mendes",
    recordedOn: "2026-06-20",
    format: "FLAC",
    location: "East Loop platform",
    summary:
      "A layered study of arriving trams, platform announcements, and departing doors.",
    audioSpec: {
      sampleRate: 96000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 187,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "metal", "rhythm"],
    color: "#2f7c75",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-courtyard",
    catalogId: "SC-26-004",
    title: "Courtyard conversation",
    source: "North Block listening circle",
    recordedOn: "2026-06-23",
    format: "WAV",
    location: "North Block courtyard",
    summary:
      "Neighbors discuss the shade trees while children play beyond the microphone.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 241,
    },
    signalRole: "voice",
    sensitivity: "restricted",
    transcriptStatus: "draft",
    consentStatus: "pending",
    isFeatured: true,
    tags: ["oral history", "neighborhood", "care"],
    color: "#c7903d",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-drain",
    catalogId: "SC-26-005",
    title: "Storm drain resonance",
    source: "Riverside youth lab",
    recordedOn: "2026-06-26",
    format: "WAV",
    location: "Canal walk",
    summary:
      "Rainwater and passing trains turn the storm drain into a low, shifting instrument.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 201,
    },
    signalRole: "voice",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["water", "weather", "youth"],
    color: "#3f6fa8",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-workshop",
    catalogId: "SC-26-006",
    title: "Ceramic workshop pulse",
    source: "Jae Min",
    recordedOn: "2026-07-01",
    format: "FLAC",
    location: "Clay Lane studios",
    summary:
      "Throwing wheels, trimming tools, and a quiet count-in before firing.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 166,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["craft", "hands", "rhythm"],
    color: "#8c9474",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-bus",
    catalogId: "SC-26-007",
    title: "Evening bus loop",
    source: "Milo Chen",
    recordedOn: "2026-07-04",
    format: "WAV",
    location: "Route 11 terminus",
    summary:
      "The last loop of the evening: ticket beeps, a driver’s goodbye, and an emptying carriage.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 193,
    },
    signalRole: "departure",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "evening", "routine"],
    color: "#a55f72",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-park",
    catalogId: "SC-26-008",
    title: "Park fence harmonics",
    source: "Elena Matic",
    recordedOn: "2026-07-08",
    format: "WAV",
    location: "Juniper Park",
    summary:
      "Wind and a loose fence panel make a soft tonal figure beside an afternoon game.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 128,
    },
    signalRole: "departure",
    sensitivity: "sensitive",
    transcriptStatus: "missing",
    consentStatus: "restricted",
    isFeatured: false,
    tags: ["park", "wind", "play"],
    color: "#597b8e",
    importBatchId: FIELD_BATCH_ID,
    lifecycle: lifecycle("active-recording", stamp),
    createdAt: stamp,
    updatedAt: stamp,
  },
  // Expired, unplaced material left over from an unfinished autumn import.
  {
    id: "rec-belltower",
    catalogId: "SC-25-090",
    title: "Old belltower ambience",
    source: "Harbor history walk",
    recordedOn: "2025-11-02",
    format: "WAV",
    location: "Harbor belltower",
    summary:
      "Distant bells and gulls recorded during a scouting walk that never became a route.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 172,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "pending",
    isFeatured: false,
    tags: ["archive-candidate", "harbor"],
    color: "#8a8f98",
    importBatchId: AUTUMN_BATCH_ID,
    lifecycle: lifecycle("active-recording", "2025-11-10T09:00:00.000Z", "expired"),
    createdAt: "2025-11-10T09:00:00.000Z",
    updatedAt: "2025-11-10T09:00:00.000Z",
  },
  // An archived clip, parked out of the route but restorable.
  {
    id: "rec-ferry-horn",
    catalogId: "SC-25-077",
    title: "Ferry horn practice take",
    source: "Harbor history walk",
    recordedOn: "2025-10-21",
    format: "WAV",
    location: "Pier 4",
    summary:
      "A rehearsal take with handling noise; kept while the harbor route was still being considered.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 143,
    },
    signalRole: "departure",
    sensitivity: "public",
    transcriptStatus: "draft",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["harbor", "take"],
    color: "#9aa3ad",
    importBatchId: AUTUMN_BATCH_ID,
    lifecycle: lifecycle(
      "active-recording",
      "2025-10-22T09:00:00.000Z",
      "archived",
      { archivedAt: "2026-06-02T08:00:00.000Z" },
    ),
    createdAt: "2025-10-22T09:00:00.000Z",
    updatedAt: "2025-11-05T09:00:00.000Z",
  },
];
const sites: Site[] = [
  {
    id: "site-threshold",
    name: "Threshold listening",
    shortLabel: "Threshold",
    prompt:
      "What changes when you stop and listen before crossing into the neighborhood?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#d7654e",
    sequence: 0,
    recordingIds: ["rec-underpass"],
    lifecycle: lifecycle("route-site", stamp),
  },
  {
    id: "site-rhythm",
    name: "Daily rhythms",
    shortLabel: "Rhythms",
    prompt:
      "Which repeated sounds tell us how work, transit, and care share a day?",
    maxDurationSeconds: 540,
    maxClips: 3,
    quietSpace: false,
    hasSeating: true,
    color: "#7c6aa6",
    sequence: 1,
    recordingIds: ["rec-market", "rec-tram"],
    lifecycle: lifecycle("route-site", stamp),
  },
  {
    id: "site-voices",
    name: "Shared voices",
    shortLabel: "Voices",
    prompt:
      "Whose voices need context, consent, or a slower place to be heard?",
    maxDurationSeconds: 480,
    maxClips: 2,
    quietSpace: true,
    hasSeating: true,
    color: "#2f7c75",
    sequence: 2,
    recordingIds: ["rec-courtyard"],
    lifecycle: lifecycle("route-site", stamp),
  },
  {
    id: "site-return",
    name: "Return and release",
    shortLabel: "Return",
    prompt: "What should remain audible after the route ends?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#597b8e",
    sequence: 3,
    recordingIds: ["rec-bus"],
    lifecycle: lifecycle("route-site", stamp),
  },
  // A site no longer in use. It still cites a clip that has since been
  // physically purged; the citation resolves through a tombstone/snapshot.
  {
    id: "site-old-harbor",
    name: "Harbor loop (paused)",
    shortLabel: "Old harbor",
    prompt: "How did the working harbor frame the city's arrival?",
    maxDurationSeconds: 360,
    maxClips: 2,
    quietSpace: false,
    hasSeating: true,
    color: "#9aa3ad",
    sequence: 4,
    recordingIds: ["rec-rain-basement"],
    lifecycle: lifecycle(
      "route-site",
      "2025-10-22T09:00:00.000Z",
      "archived",
      { archivedAt: "2026-06-02T08:00:00.000Z" },
    ),
  },
];

const importBatches: ImportBatch[] = [
  {
    id: FIELD_BATCH_ID,
    label: "Summer neighborhood fieldwork",
    source: "Field team SD cards",
    importedAt: "2026-06-14T08:00:00.000Z",
    recordingIds: [
      "rec-underpass",
      "rec-market",
      "rec-tram",
      "rec-courtyard",
      "rec-drain",
      "rec-workshop",
      "rec-bus",
      "rec-park",
    ],
  },
  {
    // An unfinished import: one clip expired, one was cleaned, and the batch
    // manifest itself is past its 90-day window.
    id: AUTUMN_BATCH_ID,
    label: "Autumn harbor intake (incomplete)",
    source: "Harbor history walk recorder",
    importedAt: "2025-10-22T08:00:00.000Z",
    recordingIds: ["rec-ferry-horn", "rec-belltower", "rec-rain-basement"],
    note: "Import stalled during consent review; never attached to a route.",
  },
];

const purgedRainBasement: Recording = {
  id: "rec-rain-basement",
  catalogId: "SC-25-061",
  title: "Rain on basement grating",
  source: "Harbor history walk",
  recordedOn: "2025-10-18",
  format: "WAV",
  location: "Pier 4 basement access",
  summary: "Rain striking a metal basement grating beside the old ferry pier.",
  audioSpec: {
    sampleRate: 48000,
    channels: 2,
    bitDepth: 24,
    durationSeconds: 96,
  },
  signalRole: "texture",
  sensitivity: "public",
  transcriptStatus: "verified",
  consentStatus: "confirmed",
  isFeatured: false,
  tags: ["harbor", "rain"],
  color: "#9aa3ad",
  importBatchId: AUTUMN_BATCH_ID,
  lifecycle: lifecycle(
    "active-recording",
    "2025-10-22T09:00:00.000Z",
    "archived",
    { archivedAt: "2026-06-02T08:00:00.000Z" },
  ),
  createdAt: "2025-10-22T09:00:00.000Z",
  updatedAt: "2025-11-02T09:00:00.000Z",
};

// A published version from a previous study year. It freezes a copy of the
// since-purged clip inside its snapshot, so the old release and its citations
// remain fully resolvable even though the live library no longer holds it.
const historicalRelease: ReleaseRecord = {
  id: "release-2025-harbor",
  sequence: 1,
  createdAt: "2025-12-15T10:00:00.000Z",
  status: "ready",
  revision: 42,
  fingerprint: "sc-r1-historical",
  readiness: {
    ready: true,
    score: 94,
    blockers: [],
    cautions: ["1 non-critical finding remains open."],
    checkedAt: "2025-12-15T10:00:00.000Z",
  },
  snapshot: {
    schemaVersion: 2,
    generatedAt: "2025-12-15T10:00:00.000Z",
    releaseId: "release-2025-harbor",
    releaseSequence: 1,
    revision: 42,
    fingerprint: "sc-r1-historical",
    project: {
      id: "signal-commons-2025-harbor",
      title: "Harbor Listening Loop 2025",
      fieldArea: "Old harbor district",
      listeningQuestion: "What did the harbor carry into the city?",
      publicationDate: "2025-12-20",
      stage: "ready",
      lastReadinessCheck: "2025-12-15T10:00:00.000Z",
    },
    preferences: { pace: "steady", accessPriority: 60, listenerCount: 5 },
    summary: {
      recordingCount: 1,
      siteCount: 1,
      routeSeconds: 96,
      readinessScore: 94,
    },
    sites: [
      {
        ...sites[4],
        recordings: [purgedRainBasement],
      },
    ],
    unresolvedIssues: [],
  },
};

export function createSeedStudy(): StudyState {
  return structuredClone({
    version: 3,
    revision: 0,
    updatedAt: stamp,
    project: {
      id: "signal-commons-2026",
      title: "Signal Commons: Listening Across the City",
      fieldArea: "Riverside neighborhoods",
      listeningQuestion:
        "How do everyday crossings, work, and care sound when residents lead the record?",
      publicationDate: "2026-10-02",
      stage: "review",
    },
    recordings,
    sites,
    issues: [
      {
        id: "issue-consent",
        title: "Confirm courtyard release scope",
        description:
          "The listening circle needs to confirm whether the full conversation can be included in the public route.",
        severity: "critical",
        status: "open",
        recordingId: "rec-courtyard",
        siteId: "site-voices",
        owner: "Amina Patel",
        lifecycle: lifecycle("quality-finding", stamp),
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "issue-transcript",
        title: "Add transcript for storm drain clip",
        description:
          "Prepare a concise transcript and sound description before the youth lab clip is released.",
        severity: "warning",
        status: "in-progress",
        recordingId: "rec-drain",
        owner: "Lin Qiao",
        lifecycle: lifecycle("quality-finding", stamp),
        createdAt: stamp,
        updatedAt: stamp,
      },
      // The retirement note for the old harbor site. The site and one of its
      // clips have been cleaned, but this finding is retained within its own
      // window and keeps pointing at them so reviewers can still see why the
      // site was stopped.
      {
        id: "issue-old-harbor-note",
        title: "Harbor loop retirement: pier access closed",
        description:
          "The harbor loop was stopped after the pier basement access was fenced off; the seating point is no longer reachable for public walks.",
        severity: "note",
        status: "resolved",
        siteId: "site-old-harbor",
        recordingId: "rec-rain-basement",
        owner: "Milo Chen",
        resolvedAt: "2026-08-20T10:00:00.000Z",
        lifecycle: lifecycle(
          "quality-finding",
          "2026-08-20T10:00:00.000Z",
          "within-retention",
        ),
        createdAt: "2026-08-12T10:00:00.000Z",
        updatedAt: "2026-08-20T10:00:00.000Z",
      },
    ],
    importBatches,
    tombstones: [
      {
        id: "rec-rain-basement",
        kind: "recording",
        label: "Rain on basement grating",
        category: "active-recording",
        purgedAt: "2026-07-01T08:00:00.000Z",
        reason: "expired-purge",
        referencedByReleaseIds: ["release-2025-harbor"],
        importBatchId: AUTUMN_BATCH_ID,
      },
    ],
    preferences: { pace: "steady", accessPriority: 70, listenerCount: 6 },
    auditLog: [],
    release: null,
    releaseHistory: [historicalRelease],
  });
}
